"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-18 12:08:58.797723
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
from app.db import rls

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TENANT_TABLES = [
    "organizations", "usage_records", "metric_snapshots", "tenant_memberships", "api_tokens",
    "scope_entries", "secrets", "assets", "asset_relationships", "asset_observations", "asset_events",
    "scans", "scan_stages", "scope_decisions", "scan_schedules", "scan_artifacts", "findings",
    "finding_activities", "integrations", "notification_policies", "notification_deliveries", "reports",
]


def apply_rls() -> None:
    statements: list[str] = []
    for table in TENANT_TABLES:
        statements += rls.tenant_isolation(table)
    statements += rls.scan_profiles_policy()
    statements += rls.audit_logs_policy()
    statements += rls.users_policy()
    statements += rls.tenants_policy()
    for table in ("user_sessions", "password_reset_tokens"):
        statements += rls.private_tables_policy(table)
    for stmt in statements:
        op.execute(stmt)


def upgrade() -> None:
    # Trigram index support for fast substring search in the asset inventory
    # (pg_trgm is a "trusted" extension: the database owner may create it).
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    upgrade_tables()
    apply_rls()


def upgrade_tables() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intel_feed_state',
    sa.Column('feed', sa.String(length=32), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('etag', sa.String(length=256), nullable=True),
    sa.Column('records', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('feed', name=op.f('pk_intel_feed_state'))
    )
    op.create_table('plans',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('max_organizations', sa.Integer(), nullable=True),
    sa.Column('max_assets', sa.Integer(), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('max_scans_per_day', sa.Integer(), nullable=True),
    sa.Column('max_concurrent_scans', sa.Integer(), nullable=False),
    sa.Column('allow_active_scanning', sa.Boolean(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('billing_interval', sa.String(length=16), nullable=True),
    sa.Column('price_minor_units', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plans')),
    sa.UniqueConstraint('code', name=op.f('uq_plans_code'))
    )
    op.create_table('vuln_intel',
    sa.Column('cve_id', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('cvss_vector', sa.String(length=256), nullable=True),
    sa.Column('cvss_version', sa.String(length=8), nullable=True),
    sa.Column('epss_score', sa.Float(), nullable=True),
    sa.Column('epss_percentile', sa.Float(), nullable=True),
    sa.Column('epss_date', sa.Date(), nullable=True),
    sa.Column('kev', sa.Boolean(), nullable=False),
    sa.Column('kev_date_added', sa.Date(), nullable=True),
    sa.Column('kev_due_date', sa.Date(), nullable=True),
    sa.Column('kev_ransomware', sa.Boolean(), nullable=False),
    sa.Column('kev_vendor', sa.String(length=200), nullable=True),
    sa.Column('kev_product', sa.String(length=200), nullable=True),
    sa.Column('exploit_available', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('cve_id', name=op.f('pk_vuln_intel'))
    )
    op.create_table('tenants',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', name='tenantstatus', native_enum=False, length=32), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('worker_pool', sa.String(length=64), nullable=False),
    sa.Column('data_region', sa.String(length=64), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('billing', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_tenants_plan_id_plans'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants')),
    sa.UniqueConstraint('slug', name=op.f('uq_tenants_slug'))
    )
    op.create_table('notification_policies',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('event_types', postgresql.ARRAY(sa.String(length=48)), nullable=False),
    sa.Column('min_severity', sa.Enum('info', 'low', 'medium', 'high', 'critical', name='severity', native_enum=False, length=32), nullable=False),
    sa.Column('organization_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('integration_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('include_baseline', sa.Boolean(), nullable=False),
    sa.Column('throttle_minutes', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_notification_policies_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_policies'))
    )
    op.create_index(op.f('ix_notification_policies_tenant_id'), 'notification_policies', ['tenant_id'], unique=False)
    op.create_table('organizations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('baseline_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_organizations_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('tenant_id', 'name', name=op.f('uq_organizations_tenant_id_name'))
    )
    op.create_index(op.f('ix_organizations_tenant_id'), 'organizations', ['tenant_id'], unique=False)
    op.create_table('usage_records',
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('period', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_usage_records_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_records'))
    )
    op.create_index(op.f('ix_usage_records_metric'), 'usage_records', ['metric'], unique=False)
    op.create_index(op.f('ix_usage_records_period'), 'usage_records', ['period'], unique=False)
    op.create_index(op.f('ix_usage_records_tenant_id'), 'usage_records', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_platform_admin', sa.Boolean(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret_encrypted', sa.String(length=512), nullable=True),
    sa.Column('auth_provider', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('default_tenant_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['default_tenant_id'], ['tenants.id'], name=op.f('fk_users_default_tenant_id_tenants'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('api_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('token_prefix', sa.String(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('platform_admin', 'tenant_admin', 'security_analyst', 'viewer', name='role', native_enum=False, length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_api_tokens_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_api_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_api_tokens_token_hash'))
    )
    op.create_index(op.f('ix_api_tokens_tenant_id'), 'api_tokens', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_api_tokens_user_id'), 'api_tokens', ['user_id'], unique=False)
    op.create_table('assets',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.Enum('root_domain', 'domain', 'subdomain', 'ip_address', 'cidr', 'asn', 'dns_record', 'certificate', 'port', 'service', 'http_endpoint', 'web_application', 'technology', 'cloud_resource', name='assettype', native_enum=False, length=32), nullable=False),
    sa.Column('value', sa.String(length=2048), nullable=False),
    sa.Column('normalized_value', sa.String(length=2048), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='assetstatus', native_enum=False, length=32), nullable=False),
    sa.Column('scope_status', sa.Enum('in_scope', 'derived', 'out_of_scope', name='scopestatus', native_enum=False, length=32), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inactive_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('missed_count', sa.SmallInteger(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('sources', postgresql.ARRAY(sa.String(length=64)), nullable=False),
    sa.Column('discovery_method', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.SmallInteger(), nullable=False),
    sa.Column('owner', sa.String(length=200), nullable=True),
    sa.Column('business_unit', sa.String(length=200), nullable=True),
    sa.Column('criticality', sa.Enum('low', 'medium', 'high', 'critical', name='criticality', native_enum=False, length=32), nullable=False),
    sa.Column('approval_status', sa.Enum('unverified', 'approved', 'expected', 'third_party', 'unknown', 'unauthorized', 'decommissioned', name='approvalstatus', native_enum=False, length=32), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=64)), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('risk_score', sa.SmallInteger(), nullable=False),
    sa.Column('risk_level', sa.Enum('info', 'low', 'medium', 'high', 'critical', name='risklevel', native_enum=False, length=32), nullable=False),
    sa.Column('risk_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('open_findings', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_assets_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_assets_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets')),
    sa.UniqueConstraint('tenant_id', 'organization_id', 'asset_type', 'normalized_value', name=op.f('uq_assets_tenant_id_organization_id_asset_type_normalized_value'))
    )
    op.create_index('ix_assets_first_seen', 'assets', ['tenant_id', 'first_seen'], unique=False)
    op.create_index('ix_assets_org_status', 'assets', ['organization_id', 'status'], unique=False)
    op.create_index('ix_assets_risk', 'assets', ['tenant_id', 'risk_score'], unique=False)
    op.create_index('ix_assets_tags', 'assets', ['tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_assets_tenant_id'), 'assets', ['tenant_id'], unique=False)
    op.create_index('ix_assets_tenant_type_status', 'assets', ['tenant_id', 'asset_type', 'status'], unique=False)
    op.create_index('ix_assets_value_trgm', 'assets', ['normalized_value'], unique=False, postgresql_using='gin', postgresql_ops={'normalized_value': 'gin_trgm_ops'})
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('actor', sa.String(length=320), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('object_type', sa.String(length=64), nullable=True),
    sa.Column('object_id', sa.String(length=64), nullable=True),
    sa.Column('previous', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_audit_logs_tenant_id_tenants'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_tenant_created', 'audit_logs', ['tenant_id', 'created_at'], unique=False)
    op.create_table('metric_snapshots',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('total_assets', sa.Integer(), nullable=False),
    sa.Column('active_assets', sa.Integer(), nullable=False),
    sa.Column('new_assets', sa.Integer(), nullable=False),
    sa.Column('unknown_assets', sa.Integer(), nullable=False),
    sa.Column('open_findings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_metric_snapshots_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_metric_snapshots_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_snapshots')),
    sa.UniqueConstraint('tenant_id', 'organization_id', 'day', name=op.f('uq_metric_snapshots_tenant_id_organization_id_day'))
    )
    op.create_index(op.f('ix_metric_snapshots_organization_id'), 'metric_snapshots', ['organization_id'], unique=False)
    op.create_index(op.f('ix_metric_snapshots_tenant_id'), 'metric_snapshots', ['tenant_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('requested_ip', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_reset_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_password_reset_tokens_token_hash'))
    )
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('reports',
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('report_type', sa.Enum('executive', 'technical', 'asset_inventory', 'vulnerability', 'changes', 'risk_trend', name='reporttype', native_enum=False, length=32), nullable=False),
    sa.Column('report_format', sa.Enum('html', 'pdf', 'csv', name='reportformat', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='jobstatus', native_enum=False, length=32), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_reports_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_reports_requested_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_reports_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index(op.f('ix_reports_tenant_id'), 'reports', ['tenant_id'], unique=False)
    op.create_table('scan_profiles',
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('is_active_scanning', sa.Boolean(), nullable=False),
    sa.Column('retain_raw_output', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_scan_profiles_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_scan_profiles_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_profiles')),
    sa.UniqueConstraint('tenant_id', 'slug', name=op.f('uq_scan_profiles_tenant_id_slug'))
    )
    op.create_index(op.f('ix_scan_profiles_tenant_id'), 'scan_profiles', ['tenant_id'], unique=False)
    op.create_table('scope_entries',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('entry_type', sa.Enum('domain', 'ip', 'cidr', name='scopeentrytype', native_enum=False, length=32), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('include_subdomains', sa.Boolean(), nullable=False),
    sa.Column('is_exclusion', sa.Boolean(), nullable=False),
    sa.Column('allow_active_scanning', sa.Boolean(), nullable=False),
    sa.Column('verification_status', sa.Enum('unverified', 'pending', 'verified', 'not_required', name='verificationstatus', native_enum=False, length=32), nullable=False),
    sa.Column('verification_token', sa.String(length=128), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_scope_entries_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_scope_entries_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_scope_entries_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scope_entries')),
    sa.UniqueConstraint('tenant_id', 'organization_id', 'entry_type', 'value', 'is_exclusion', name=op.f('uq_scope_entries_tenant_id_organization_id_entry_type_value_is_exclusion'))
    )
    op.create_index(op.f('ix_scope_entries_organization_id'), 'scope_entries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_scope_entries_tenant_id'), 'scope_entries', ['tenant_id'], unique=False)
    op.create_table('secrets',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('backend', sa.String(length=32), nullable=False),
    sa.Column('ciphertext', sa.Text(), nullable=True),
    sa.Column('external_ref', sa.String(length=512), nullable=True),
    sa.Column('key_id', sa.String(length=32), nullable=True),
    sa.Column('last_four', sa.String(length=8), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_secrets_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_secrets_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_secrets')),
    sa.UniqueConstraint('tenant_id', 'name', name=op.f('uq_secrets_tenant_id_name'))
    )
    op.create_index(op.f('ix_secrets_tenant_id'), 'secrets', ['tenant_id'], unique=False)
    op.create_table('tenant_memberships',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('platform_admin', 'tenant_admin', 'security_analyst', 'viewer', name='role', native_enum=False, length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tenant_memberships_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tenant_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_memberships')),
    sa.UniqueConstraint('tenant_id', 'user_id', name=op.f('uq_tenant_memberships_tenant_id_user_id'))
    )
    op.create_index(op.f('ix_tenant_memberships_tenant_id'), 'tenant_memberships', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tenant_memberships_user_id'), 'tenant_memberships', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('refresh_token_hash', sa.String(length=128), nullable=False),
    sa.Column('previous_token_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('absolute_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('mfa_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_user_sessions_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions')),
    sa.UniqueConstraint('refresh_token_hash', name=op.f('uq_user_sessions_refresh_token_hash'))
    )
    op.create_index(op.f('ix_user_sessions_previous_token_hash'), 'user_sessions', ['previous_token_hash'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('asset_relationships',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('source_asset_id', sa.UUID(), nullable=False),
    sa.Column('target_asset_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.Enum('resolves_to', 'cname', 'ns_record', 'mx_record', 'ptr', 'subdomain_of', 'contains', 'announces', 'belongs_to_asn', 'has_port', 'runs_service', 'serves', 'hosted_on', 'uses_technology', 'presents_certificate', 'certificate_for', 'hosted_by', 'redirects_to', 'related_to', name='relationtype', native_enum=False, length=32), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('missed_count', sa.SmallInteger(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_asset_relationships_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_asset_id'], ['assets.id'], name=op.f('fk_asset_relationships_source_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_asset_id'], ['assets.id'], name=op.f('fk_asset_relationships_target_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_asset_relationships_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_relationships')),
    sa.UniqueConstraint('source_asset_id', 'target_asset_id', 'relation_type', name=op.f('uq_asset_relationships_source_asset_id_target_asset_id_relation_type'))
    )
    op.create_index('ix_asset_rel_source', 'asset_relationships', ['source_asset_id', 'relation_type', 'active'], unique=False)
    op.create_index('ix_asset_rel_target', 'asset_relationships', ['target_asset_id', 'relation_type'], unique=False)
    op.create_index(op.f('ix_asset_relationships_tenant_id'), 'asset_relationships', ['tenant_id'], unique=False)
    op.create_table('integrations',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('integration_type', sa.Enum('email', 'webhook', 'wazuh', 'slack', 'teams', 'jira', 'servicenow', name='integrationtype', native_enum=False, length=32), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('secret_id', sa.UUID(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_integrations_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['secret_id'], ['secrets.id'], name=op.f('fk_integrations_secret_id_secrets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_integrations_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integrations'))
    )
    op.create_index(op.f('ix_integrations_tenant_id'), 'integrations', ['tenant_id'], unique=False)
    op.create_table('scan_schedules',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('cron', sa.String(length=64), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_scan_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_scan_schedules_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_scan_schedules_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['scan_profiles.id'], name=op.f('fk_scan_schedules_profile_id_scan_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_scan_schedules_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_schedules'))
    )
    op.create_index(op.f('ix_scan_schedules_next_run_at'), 'scan_schedules', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_scan_schedules_organization_id'), 'scan_schedules', ['organization_id'], unique=False)
    op.create_index(op.f('ix_scan_schedules_tenant_id'), 'scan_schedules', ['tenant_id'], unique=False)
    op.create_table('scans',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('profile_name', sa.String(length=128), nullable=False),
    sa.Column('profile_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('pending', 'queued', 'running', 'completed', 'partial', 'failed', 'cancelled', name='scanstatus', native_enum=False, length=32), nullable=False),
    sa.Column('trigger', sa.Enum('manual', 'scheduled', 'api', name='scantrigger', native_enum=False, length=32), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('schedule_id', sa.UUID(), nullable=True),
    sa.Column('target_override', postgresql.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('is_baseline', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_scans_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['scan_profiles.id'], name=op.f('fk_scans_profile_id_scan_profiles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_scans_requested_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_id'], ['scan_schedules.id'], name=op.f('fk_scans_schedule_id_scan_schedules'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_scans_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scans'))
    )
    op.create_index('ix_scans_org_created', 'scans', ['organization_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_scans_tenant_id'), 'scans', ['tenant_id'], unique=False)
    op.create_index('ix_scans_tenant_status', 'scans', ['tenant_id', 'status'], unique=False)
    op.create_table('findings',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_finding_id', sa.String(length=512), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('vulnerability', 'exposure', 'misconfiguration', 'certificate', 'service_exposure', 'information', 'credential_leak', name='findingcategory', native_enum=False, length=32), nullable=False),
    sa.Column('severity', sa.Enum('info', 'low', 'medium', 'high', 'critical', name='severity', native_enum=False, length=32), nullable=False),
    sa.Column('location', sa.String(length=1024), nullable=True),
    sa.Column('cve', postgresql.ARRAY(sa.String(length=32)), nullable=False),
    sa.Column('cwe', postgresql.ARRAY(sa.String(length=32)), nullable=False),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('cvss_vector', sa.String(length=256), nullable=True),
    sa.Column('epss_score', sa.Float(), nullable=True),
    sa.Column('epss_percentile', sa.Float(), nullable=True),
    sa.Column('kev', sa.Boolean(), nullable=False),
    sa.Column('kev_due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exploit_available', sa.Boolean(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('references', postgresql.ARRAY(sa.String(length=1024)), nullable=False),
    sa.Column('confidence', sa.SmallInteger(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_scan_id', sa.UUID(), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('missed_count', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.Enum('new', 'investigating', 'accepted_risk', 'false_positive', 'remediated', 'reopened', name='findingstatus', native_enum=False, length=32), nullable=False),
    sa.Column('false_positive', sa.Boolean(), nullable=False),
    sa.Column('accepted_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=64)), nullable=False),
    sa.Column('risk_score', sa.SmallInteger(), nullable=False),
    sa.Column('risk_level', sa.Enum('info', 'low', 'medium', 'high', 'critical', name='risklevel', native_enum=False, length=32), nullable=False),
    sa.Column('risk_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_findings_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('fk_findings_assigned_to_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_scan_id'], ['scans.id'], name=op.f('fk_findings_last_scan_id_scans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_findings_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_findings_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_findings')),
    sa.UniqueConstraint('tenant_id', 'fingerprint', name=op.f('uq_findings_tenant_id_fingerprint'))
    )
    op.create_index('ix_findings_asset', 'findings', ['asset_id'], unique=False)
    op.create_index('ix_findings_cve', 'findings', ['cve'], unique=False, postgresql_using='gin')
    op.create_index('ix_findings_risk', 'findings', ['tenant_id', 'risk_score'], unique=False)
    op.create_index(op.f('ix_findings_tenant_id'), 'findings', ['tenant_id'], unique=False)
    op.create_index('ix_findings_tenant_status_sev', 'findings', ['tenant_id', 'status', 'severity'], unique=False)
    op.create_table('scan_stages',
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('stage_type', sa.Enum('subdomain_discovery', 'dns_resolution', 'ip_enrichment', 'port_discovery', 'http_discovery', 'vulnerability_detection', 'osint_enrichment', name='stagetype', native_enum=False, length=32), nullable=False),
    sa.Column('engine', sa.String(length=64), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'partial', 'failed', 'skipped', 'cancelled', name='stagestatus', native_enum=False, length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('target_count', sa.Integer(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.Column('observation_count', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tool_version', sa.String(length=64), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_scan_stages_scan_id_scans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_scan_stages_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_stages')),
    sa.UniqueConstraint('scan_id', 'position', name=op.f('uq_scan_stages_scan_id_position'))
    )
    op.create_index(op.f('ix_scan_stages_scan_id'), 'scan_stages', ['scan_id'], unique=False)
    op.create_index(op.f('ix_scan_stages_tenant_id'), 'scan_stages', ['tenant_id'], unique=False)
    op.create_table('asset_events',
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('asset_type', sa.Enum('root_domain', 'domain', 'subdomain', 'ip_address', 'cidr', 'asn', 'dns_record', 'certificate', 'port', 'service', 'http_endpoint', 'web_application', 'technology', 'cloud_resource', name='assettype', native_enum=False, length=32), nullable=True),
    sa.Column('asset_value', sa.String(length=2048), nullable=True),
    sa.Column('finding_id', sa.UUID(), nullable=True),
    sa.Column('scan_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Enum('new_asset', 'new_subdomain', 'asset_disappeared', 'asset_reappeared', 'dns_changed', 'ip_changed', 'port_opened', 'port_closed', 'service_detected', 'service_changed', 'certificate_changed', 'certificate_expiring', 'certificate_expired', 'technology_detected', 'technology_removed', 'vulnerability_detected', 'vulnerability_resolved', 'vulnerability_reopened', 'risk_increased', 'risk_decreased', 'asset_exposed', 'ownership_changed', 'approval_changed', 'hosting_changed', 'shadow_it_discovered', 'scan_failed', 'scan_completed', name='eventtype', native_enum=False, length=48), nullable=False),
    sa.Column('severity', sa.Enum('info', 'low', 'medium', 'high', 'critical', name='severity', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('previous_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_baseline', sa.Boolean(), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_by', sa.UUID(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], name=op.f('fk_asset_events_acknowledged_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_events_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_asset_events_finding_id_findings'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_asset_events_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_asset_events_scan_id_scans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_asset_events_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_events'))
    )
    op.create_index(op.f('ix_asset_events_scan_id'), 'asset_events', ['scan_id'], unique=False)
    op.create_index(op.f('ix_asset_events_tenant_id'), 'asset_events', ['tenant_id'], unique=False)
    op.create_index('ix_events_asset_time', 'asset_events', ['asset_id', 'occurred_at'], unique=False)
    op.create_index('ix_events_org_type', 'asset_events', ['organization_id', 'event_type'], unique=False)
    op.create_index('ix_events_tenant_time', 'asset_events', ['tenant_id', 'occurred_at'], unique=False)
    op.create_index('ix_events_unnotified', 'asset_events', ['tenant_id', 'notified', 'is_baseline'], unique=False)
    op.create_table('asset_observations',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=True),
    sa.Column('stage_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_observations_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_asset_observations_scan_id_scans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stage_id'], ['scan_stages.id'], name=op.f('fk_asset_observations_stage_id_scan_stages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_asset_observations_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_observations'))
    )
    op.create_index('ix_asset_obs_asset_time', 'asset_observations', ['asset_id', 'observed_at'], unique=False)
    op.create_index(op.f('ix_asset_observations_scan_id'), 'asset_observations', ['scan_id'], unique=False)
    op.create_index(op.f('ix_asset_observations_tenant_id'), 'asset_observations', ['tenant_id'], unique=False)
    op.create_table('finding_activities',
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('activity_type', sa.String(length=32), nullable=False),
    sa.Column('previous', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('scan_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_finding_activities_finding_id_findings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_finding_activities_scan_id_scans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_finding_activities_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_finding_activities_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finding_activities'))
    )
    op.create_index('ix_finding_activities_finding', 'finding_activities', ['finding_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_finding_activities_tenant_id'), 'finding_activities', ['tenant_id'], unique=False)
    op.create_table('scan_artifacts',
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('stage_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('truncated', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_scan_artifacts_scan_id_scans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_id'], ['scan_stages.id'], name=op.f('fk_scan_artifacts_stage_id_scan_stages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_scan_artifacts_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_artifacts'))
    )
    op.create_index(op.f('ix_scan_artifacts_scan_id'), 'scan_artifacts', ['scan_id'], unique=False)
    op.create_index(op.f('ix_scan_artifacts_tenant_id'), 'scan_artifacts', ['tenant_id'], unique=False)
    op.create_table('scope_decisions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('stage_id', sa.UUID(), nullable=True),
    sa.Column('target', sa.String(length=2048), nullable=False),
    sa.Column('decision', sa.Enum('allowed', 'rejected', name='decisionresult', native_enum=False, length=32), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('matched_entry_id', sa.UUID(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['matched_entry_id'], ['scope_entries.id'], name=op.f('fk_scope_decisions_matched_entry_id_scope_entries'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_scope_decisions_scan_id_scans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_id'], ['scan_stages.id'], name=op.f('fk_scope_decisions_stage_id_scan_stages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_scope_decisions_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scope_decisions'))
    )
    op.create_index('ix_scope_decisions_scan', 'scope_decisions', ['scan_id', 'decision'], unique=False)
    op.create_index(op.f('ix_scope_decisions_tenant_id'), 'scope_decisions', ['tenant_id'], unique=False)
    op.create_table('notification_deliveries',
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('policy_id', sa.UUID(), nullable=True),
    sa.Column('integration_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', 'skipped', name='deliverystatus', native_enum=False, length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['asset_events.id'], name=op.f('fk_notification_deliveries_event_id_asset_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], name=op.f('fk_notification_deliveries_integration_id_integrations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_id'], ['notification_policies.id'], name=op.f('fk_notification_deliveries_policy_id_notification_policies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_notification_deliveries_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_deliveries'))
    )
    op.create_index('ix_deliveries_status', 'notification_deliveries', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_event_id'), 'notification_deliveries', ['event_id'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_tenant_id'), 'notification_deliveries', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # The users policy references tenant_memberships; drop it before the tables.
    op.execute("DROP POLICY IF EXISTS users_visibility ON users")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_deliveries_tenant_id'), table_name='notification_deliveries')
    op.drop_index(op.f('ix_notification_deliveries_event_id'), table_name='notification_deliveries')
    op.drop_index('ix_deliveries_status', table_name='notification_deliveries')
    op.drop_table('notification_deliveries')
    op.drop_index(op.f('ix_scope_decisions_tenant_id'), table_name='scope_decisions')
    op.drop_index('ix_scope_decisions_scan', table_name='scope_decisions')
    op.drop_table('scope_decisions')
    op.drop_index(op.f('ix_scan_artifacts_tenant_id'), table_name='scan_artifacts')
    op.drop_index(op.f('ix_scan_artifacts_scan_id'), table_name='scan_artifacts')
    op.drop_table('scan_artifacts')
    op.drop_index(op.f('ix_finding_activities_tenant_id'), table_name='finding_activities')
    op.drop_index('ix_finding_activities_finding', table_name='finding_activities')
    op.drop_table('finding_activities')
    op.drop_index(op.f('ix_asset_observations_tenant_id'), table_name='asset_observations')
    op.drop_index(op.f('ix_asset_observations_scan_id'), table_name='asset_observations')
    op.drop_index('ix_asset_obs_asset_time', table_name='asset_observations')
    op.drop_table('asset_observations')
    op.drop_index('ix_events_unnotified', table_name='asset_events')
    op.drop_index('ix_events_tenant_time', table_name='asset_events')
    op.drop_index('ix_events_org_type', table_name='asset_events')
    op.drop_index('ix_events_asset_time', table_name='asset_events')
    op.drop_index(op.f('ix_asset_events_tenant_id'), table_name='asset_events')
    op.drop_index(op.f('ix_asset_events_scan_id'), table_name='asset_events')
    op.drop_table('asset_events')
    op.drop_index(op.f('ix_scan_stages_tenant_id'), table_name='scan_stages')
    op.drop_index(op.f('ix_scan_stages_scan_id'), table_name='scan_stages')
    op.drop_table('scan_stages')
    op.drop_index('ix_findings_tenant_status_sev', table_name='findings')
    op.drop_index(op.f('ix_findings_tenant_id'), table_name='findings')
    op.drop_index('ix_findings_risk', table_name='findings')
    op.drop_index('ix_findings_cve', table_name='findings', postgresql_using='gin')
    op.drop_index('ix_findings_asset', table_name='findings')
    op.drop_table('findings')
    op.drop_index('ix_scans_tenant_status', table_name='scans')
    op.drop_index(op.f('ix_scans_tenant_id'), table_name='scans')
    op.drop_index('ix_scans_org_created', table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_scan_schedules_tenant_id'), table_name='scan_schedules')
    op.drop_index(op.f('ix_scan_schedules_organization_id'), table_name='scan_schedules')
    op.drop_index(op.f('ix_scan_schedules_next_run_at'), table_name='scan_schedules')
    op.drop_table('scan_schedules')
    op.drop_index(op.f('ix_integrations_tenant_id'), table_name='integrations')
    op.drop_table('integrations')
    op.drop_index(op.f('ix_asset_relationships_tenant_id'), table_name='asset_relationships')
    op.drop_index('ix_asset_rel_target', table_name='asset_relationships')
    op.drop_index('ix_asset_rel_source', table_name='asset_relationships')
    op.drop_table('asset_relationships')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_previous_token_hash'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_tenant_memberships_user_id'), table_name='tenant_memberships')
    op.drop_index(op.f('ix_tenant_memberships_tenant_id'), table_name='tenant_memberships')
    op.drop_table('tenant_memberships')
    op.drop_index(op.f('ix_secrets_tenant_id'), table_name='secrets')
    op.drop_table('secrets')
    op.drop_index(op.f('ix_scope_entries_tenant_id'), table_name='scope_entries')
    op.drop_index(op.f('ix_scope_entries_organization_id'), table_name='scope_entries')
    op.drop_table('scope_entries')
    op.drop_index(op.f('ix_scan_profiles_tenant_id'), table_name='scan_profiles')
    op.drop_table('scan_profiles')
    op.drop_index(op.f('ix_reports_tenant_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_metric_snapshots_tenant_id'), table_name='metric_snapshots')
    op.drop_index(op.f('ix_metric_snapshots_organization_id'), table_name='metric_snapshots')
    op.drop_table('metric_snapshots')
    op.drop_index('ix_audit_logs_tenant_created', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_assets_value_trgm', table_name='assets', postgresql_using='gin', postgresql_ops={'normalized_value': 'gin_trgm_ops'})
    op.drop_index('ix_assets_tenant_type_status', table_name='assets')
    op.drop_index(op.f('ix_assets_tenant_id'), table_name='assets')
    op.drop_index('ix_assets_tags', table_name='assets', postgresql_using='gin')
    op.drop_index('ix_assets_risk', table_name='assets')
    op.drop_index('ix_assets_org_status', table_name='assets')
    op.drop_index('ix_assets_first_seen', table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_api_tokens_user_id'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_tenant_id'), table_name='api_tokens')
    op.drop_table('api_tokens')
    op.drop_table('users')
    op.drop_index(op.f('ix_usage_records_tenant_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_period'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_metric'), table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index(op.f('ix_organizations_tenant_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_notification_policies_tenant_id'), table_name='notification_policies')
    op.drop_table('notification_policies')
    op.drop_table('tenants')
    op.drop_table('vuln_intel')
    op.drop_table('plans')
    op.drop_table('intel_feed_state')
    # ### end Alembic commands ###
    op.execute("DROP FUNCTION IF EXISTS asm_audit_immutable() CASCADE")
